# jozi-morning — jozi city nights
# https://github.com/kmf/jozi-city-nights

# Main bg/fg
theme[main_bg]="#d5d6db"
theme[main_fg]="#343b58"
theme[title]="#1f2335"
theme[hi_fg]="#b11565"
theme[selected_bg]="#bfc1cc"
theme[selected_fg]="#1f2335"
theme[inactive_fg]="#3f4d7d"
theme[graph_text]="#3f4d7d"
theme[meter_bg]="#72778b"
theme[proc_misc]="#4b41e4"

# Box borders
theme[cpu_box]="#7928a8"
theme[mem_box]="#166534"
theme[net_box]="#4b41e4"
theme[proc_box]="#b11565"
theme[div_line]="#72778b"

# Temperature graph gradients
theme[temp_start]="#166534"
theme[temp_mid]="#775800"
theme[temp_end]="#b11565"

# CPU graph gradients
theme[cpu_start]="#166534"
theme[cpu_mid]="#775800"
theme[cpu_end]="#b11565"

# Memory meters
theme[free_start]="#115e59"
theme[free_mid]="#155e75"
theme[free_end]="#4b41e4"
theme[cached_start]="#4b41e4"
theme[cached_mid]="#7928a8"
theme[cached_end]="#b11565"
theme[available_start]="#166534"
theme[available_mid]="#115e59"
theme[available_end]="#155e75"
theme[used_start]="#775800"
theme[used_mid]="#9d4007"
theme[used_end]="#b11565"

# Network download/upload gradients
theme[download_start]="#166534"
theme[download_mid]="#115e59"
theme[download_end]="#4b41e4"
theme[upload_start]="#7928a8"
theme[upload_mid]="#b11565"
theme[upload_end]="#9d4007"

# Process gradients
theme[process_start]="#4b41e4"
theme[process_mid]="#7928a8"
theme[process_end]="#b11565"
