# jozi-morning — jozi city nights
# https://github.com/kmf/jozi-city-nights

# Main bg/fg
theme[main_bg]="#d5d6db"
theme[main_fg]="#343b58"
theme[title]="#1f2335"
theme[hi_fg]="#a0135b"
theme[selected_bg]="#bfc1cc"
theme[selected_fg]="#1f2335"
theme[inactive_fg]="#3f4d7d"
theme[graph_text]="#3f4d7d"
theme[meter_bg]="#72778b"
theme[proc_misc]="#3b30e2"

# Box borders
theme[cpu_box]="#7928a8"
theme[mem_box]="#156031"
theme[net_box]="#3b30e2"
theme[proc_box]="#a0135b"
theme[div_line]="#72778b"

# Temperature graph gradients
theme[temp_start]="#156031"
theme[temp_mid]="#6a4f00"
theme[temp_end]="#a0135b"

# CPU graph gradients
theme[cpu_start]="#156031"
theme[cpu_mid]="#6a4f00"
theme[cpu_end]="#a0135b"

# Memory meters
theme[free_start]="#115e59"
theme[free_mid]="#145a70"
theme[free_end]="#3b30e2"
theme[cached_start]="#3b30e2"
theme[cached_mid]="#7928a8"
theme[cached_end]="#a0135b"
theme[available_start]="#156031"
theme[available_mid]="#115e59"
theme[available_end]="#145a70"
theme[used_start]="#6a4f00"
theme[used_mid]="#8f3a06"
theme[used_end]="#a0135b"

# Network download/upload gradients
theme[download_start]="#156031"
theme[download_mid]="#115e59"
theme[download_end]="#3b30e2"
theme[upload_start]="#7928a8"
theme[upload_mid]="#a0135b"
theme[upload_end]="#8f3a06"

# Process gradients
theme[process_start]="#3b30e2"
theme[process_mid]="#7928a8"
theme[process_end]="#a0135b"
