# jozi-morning — jozi city nights
# https://github.com/kmf/jozi-city-nights

background #d5d6db
foreground #343b58
selection_background #bfc1cc
selection_foreground #1f2335
cursor #b11565
cursor_text_color #d5d6db
url_color #4b41e4

active_border_color #72778b
inactive_border_color #bfc1cc
bell_border_color #b11565

active_tab_background #d5d6db
active_tab_foreground #343b58
inactive_tab_background #c8c9d1
inactive_tab_foreground #3f4d7d

# normal
color0 #343b58
color1 #b11565
color2 #166534
color3 #775800
color4 #4b41e4
color5 #7928a8
color6 #155e75
color7 #c8c9d1

# bright
color8 #3f4d7d
color9 #b11565
color10 #166534
color11 #775800
color12 #4b41e4
color13 #7928a8
color14 #155e75
color15 #343b58
