# jozi-nights — jozi city nights
# https://github.com/kmf/jozi-city-nights

background #1b1e2e
foreground #a9b1d6
selection_background #292e42
selection_foreground #c0caf5
cursor #f92aad
cursor_text_color #1b1e2e
url_color #7aa2f7

active_border_color #3b4261
inactive_border_color #24283b
bell_border_color #f92aad

active_tab_background #1b1e2e
active_tab_foreground #a9b1d6
inactive_tab_background #1f2335
inactive_tab_foreground #8089b3

# normal
color0 #414868
color1 #f92aad
color2 #54e484
color3 #e0b401
color4 #7aa2f7
color5 #b141f1
color6 #58c7e0
color7 #a9b1d6

# bright
color8 #545c7e
color9 #f92aad
color10 #54e484
color11 #e0b401
color12 #7aa2f7
color13 #b141f1
color14 #58c7e0
color15 #c0caf5
