# jozi-morning — jozi city nights
# https://github.com/kmf/jozi-city-nights

background #d5d6db
foreground #343b58
selection_background #bfc1cc
selection_foreground #1f2335
cursor #d6197a
cursor_text_color #d5d6db
url_color #4f46e5

active_border_color #b0b3be
inactive_border_color #bfc1cc
bell_border_color #d6197a

active_tab_background #d5d6db
active_tab_foreground #343b58
inactive_tab_background #c8c9d1
inactive_tab_foreground #6172af

# normal
color0 #343b58
color1 #d6197a
color2 #16864a
color3 #c49000
color4 #4f46e5
color5 #7928a8
color6 #0891b2
color7 #c8c9d1

# bright
color8 #6172af
color9 #d6197a
color10 #16864a
color11 #c49000
color12 #4f46e5
color13 #7928a8
color14 #0891b2
color15 #343b58
