# jozi-morning — jozi city nights
# https://github.com/kmf/jozi-city-nights

[cursor]
color=d5d6db d6197a

[colors]
foreground=343b58
background=d5d6db
selection-foreground=1f2335
selection-background=bfc1cc

regular0=343b58
regular1=d6197a
regular2=16864a
regular3=c49000
regular4=4f46e5
regular5=7928a8
regular6=0891b2
regular7=c8c9d1

bright0=6172af
bright1=d6197a
bright2=16864a
bright3=c49000
bright4=4f46e5
bright5=7928a8
bright6=0891b2
bright7=343b58
