# jozi-morning — jozi city nights
# https://github.com/kmf/jozi-city-nights

[cursor]
color=d5d6db b11565

[colors]
foreground=343b58
background=d5d6db
selection-foreground=1f2335
selection-background=bfc1cc

regular0=343b58
regular1=b11565
regular2=166534
regular3=775800
regular4=4b41e4
regular5=7928a8
regular6=155e75
regular7=c8c9d1

bright0=3f4d7d
bright1=b11565
bright2=166534
bright3=775800
bright4=4b41e4
bright5=7928a8
bright6=155e75
bright7=343b58
