# jozi-morning — jozi city nights
# https://github.com/kmf/jozi-city-nights

[cursor]
color=d5d6db a0135b

[colors]
foreground=343b58
background=d5d6db
selection-foreground=1f2335
selection-background=bfc1cc

regular0=343b58
regular1=a0135b
regular2=156031
regular3=6a4f00
regular4=3b30e2
regular5=7928a8
regular6=145a70
regular7=c8c9d1

bright0=3f4d7d
bright1=a0135b
bright2=156031
bright3=6a4f00
bright4=3b30e2
bright5=7928a8
bright6=145a70
bright7=343b58
