# jozi-morning — jozi city nights
# https://github.com/kmf/jozi-city-nights

[colors.primary]
background = "#d5d6db"
foreground = "#343b58"

[colors.cursor]
cursor = "#a0135b"
text = "#d5d6db"

[colors.vi_mode_cursor]
cursor = "#115e59"
text = "#d5d6db"

[colors.selection]
background = "#bfc1cc"
text = "#1f2335"

[colors.search.matches]
background = "#6a4f00"
foreground = "#d5d6db"

[colors.search.focused_match]
background = "#8f3a06"
foreground = "#d5d6db"

[colors.hints.start]
background = "#6a4f00"
foreground = "#d5d6db"

[colors.hints.end]
background = "#3f4d7d"
foreground = "#d5d6db"

[colors.footer_bar]
background = "#c8c9d1"
foreground = "#343b58"

[colors.normal]
black = "#343b58"
red = "#a0135b"
green = "#156031"
yellow = "#6a4f00"
blue = "#3b30e2"
magenta = "#7928a8"
cyan = "#145a70"
white = "#c8c9d1"

[colors.bright]
black = "#3f4d7d"
red = "#a0135b"
green = "#156031"
yellow = "#6a4f00"
blue = "#3b30e2"
magenta = "#7928a8"
cyan = "#145a70"
white = "#343b58"
