# jozi-morning — jozi city nights
# https://github.com/kmf/jozi-city-nights

[colors.primary]
background = "#d5d6db"
foreground = "#343b58"

[colors.cursor]
cursor = "#b11565"
text = "#d5d6db"

[colors.vi_mode_cursor]
cursor = "#115e59"
text = "#d5d6db"

[colors.selection]
background = "#bfc1cc"
text = "#1f2335"

[colors.search.matches]
background = "#775800"
foreground = "#d5d6db"

[colors.search.focused_match]
background = "#9d4007"
foreground = "#d5d6db"

[colors.hints.start]
background = "#775800"
foreground = "#d5d6db"

[colors.hints.end]
background = "#3f4d7d"
foreground = "#d5d6db"

[colors.footer_bar]
background = "#c8c9d1"
foreground = "#343b58"

[colors.normal]
black = "#343b58"
red = "#b11565"
green = "#166534"
yellow = "#775800"
blue = "#4b41e4"
magenta = "#7928a8"
cyan = "#155e75"
white = "#c8c9d1"

[colors.bright]
black = "#3f4d7d"
red = "#b11565"
green = "#166534"
yellow = "#775800"
blue = "#4b41e4"
magenta = "#7928a8"
cyan = "#155e75"
white = "#343b58"
